import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Lokace po celé České republice
const locations = [
  { name: 'Praha - Vyšehrad', lat: 50.0657, lng: 14.4175 },
  { name: 'Praha - Hradčany', lat: 50.0905, lng: 14.3987 },
  { name: 'Brno - Špilberk', lat: 49.1943, lng: 16.5996 },
  { name: 'Brno - okolí', lat: 49.2125, lng: 16.6234 },
  { name: 'Ostrava - Landek', lat: 49.8567, lng: 18.2632 },
  { name: 'Plzeň - okolí', lat: 49.7477, lng: 13.3776 },
  { name: 'Olomouc - centrum', lat: 49.5938, lng: 17.2509 },
  { name: 'České Budějovice', lat: 48.9745, lng: 14.4747 },
  { name: 'Liberec - okolí', lat: 50.7663, lng: 15.0543 },
  { name: 'Hradec Králové', lat: 50.2092, lng: 15.8328 },
  { name: 'Pardubice - okolí', lat: 50.0343, lng: 15.7812 },
  { name: 'Zlín - okolí', lat: 49.2247, lng: 17.6621 },
  { name: 'Jihlava', lat: 49.3961, lng: 15.5912 },
  { name: 'Tábor - okolí', lat: 49.4144, lng: 14.6579 },
  { name: 'Kutná Hora', lat: 49.9486, lng: 15.2681 },
  { name: 'Znojmo - okolí', lat: 48.8555, lng: 16.0488 },
  { name: 'Kroměříž', lat: 49.2976, lng: 17.3932 },
  { name: 'Karlovy Vary - okolí', lat: 50.2316, lng: 12.8714 },
  { name: 'Mariánské Lázně', lat: 49.9646, lng: 12.7015 },
  { name: 'Telč', lat: 49.1843, lng: 15.4529 },
];

// Mince - 6 nálezů
const coinFindings = [
  {
    title: 'Stříbrný groš Václava IV.',
    category: 'numismatika',
    findingType: 'COIN',
    description: 'Dobře zachovalý stříbrný groš z doby vlády Václava IV. Jasně čitelný nápis WENCESLAVS DEI GRACIA. Na reverzu český lev.',
    condition: 'Velmi dobrá',
    material: 'Stříbro',
    period: 'Pozdní středověk',
    periodFrom: 1378,
    periodTo: 1419,
    weight: 2.8,
    dimensions: '24mm průměr',
    denomination: 'Groš',
    mintYear: 1395,
    mint: 'Kutná Hora',
    catalogNumber: 'Castelin 21',
    grade: 'VF',
    depth: 15,
    historicalContext: 'Období vlády Václava IV., syna Karla IV.',
  },
  {
    title: 'Dukát Ferdinanda III.',
    category: 'numismatika',
    findingType: 'COIN',
    description: 'Zlatý dukát z roku 1648, velmi vzácný exemplář. Portrét Ferdinanda III. na averzu.',
    condition: 'Výborná',
    material: 'Zlato',
    period: 'Baroko',
    periodFrom: 1637,
    periodTo: 1657,
    weight: 3.5,
    dimensions: '21mm průměr',
    denomination: 'Dukát',
    mintYear: 1648,
    mint: 'Praha',
    catalogNumber: 'F.173',
    grade: 'XF',
    depth: 8,
    historicalContext: 'Konec třicetileté války, rok Vestfálského míru.',
  },
  {
    title: 'Krejcar Marie Terezie',
    category: 'numismatika',
    findingType: 'COIN',
    description: 'Měděný krejcar s portrétem Marie Terezie. Běžná oběhová mince.',
    condition: 'Dobrá',
    material: 'Měď',
    period: 'Osvícenství',
    periodFrom: 1740,
    periodTo: 1780,
    weight: 8.2,
    dimensions: '27mm průměr',
    denomination: 'Krejcar',
    mintYear: 1762,
    mint: 'Vídeň',
    catalogNumber: 'KM-2057',
    grade: 'F',
    depth: 20,
    historicalContext: 'Období vlády Marie Terezie a reforem.',
  },
  {
    title: 'Denár Přemysla Otakara II.',
    category: 'numismatika',
    findingType: 'COIN',
    description: 'Stříbrný denár Přemysla Otakara II., tzv. "Železného a zlatého krále". Unikátní nález.',
    condition: 'Velmi dobrá',
    material: 'Stříbro',
    period: 'Vrcholný středověk',
    periodFrom: 1253,
    periodTo: 1278,
    weight: 0.9,
    dimensions: '16mm průměr',
    denomination: 'Denár',
    mintYear: 1265,
    mint: 'Praha',
    catalogNumber: 'Cach 875',
    grade: 'VF+',
    depth: 25,
    historicalContext: 'Doba největšího rozmachu českého království.',
  },
  {
    title: 'Tolar Rudolfa II.',
    category: 'numismatika',
    findingType: 'COIN',
    description: 'Stříbrný tolar s portrétem císaře Rudolfa II. Krásná patina.',
    condition: 'Výborná',
    material: 'Stříbro',
    period: 'Renesance',
    periodFrom: 1576,
    periodTo: 1612,
    weight: 28.5,
    dimensions: '42mm průměr',
    denomination: 'Tolar',
    mintYear: 1603,
    mint: 'Kutná Hora',
    catalogNumber: 'Hal.371',
    grade: 'XF',
    depth: 12,
    historicalContext: 'Období vlády Rudolfa II. a rozkvětu kultury v Praze.',
  },
  {
    title: '10 haléřů První republika',
    category: 'numismatika',
    findingType: 'COIN',
    description: 'Bronzová mince 10 haléřů z roku 1928 s lvem a lipovými ratolestmi.',
    condition: 'Dobrá',
    material: 'Bronz',
    period: 'První republika',
    periodFrom: 1918,
    periodTo: 1938,
    weight: 2.0,
    dimensions: '19mm průměr',
    denomination: '10 haléřů',
    mintYear: 1928,
    mint: 'Kremnice',
    catalogNumber: 'KM-3',
    grade: 'VF',
    depth: 18,
    historicalContext: 'Období první Československé republiky.',
  },
];

// Známky - 10 nálezů
const stampFindings = [
  {
    title: 'Hradčany 5h - nezoubkovaná',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Nezoubkovaná známka Hradčany 5 haléřů z roku 1918. Alfons Mucha design. Vzácná varianta.',
    condition: 'Výborná',
    material: 'Papír',
    period: 'Vznik ČSR',
    periodFrom: 1918,
    periodTo: 1920,
    stampYear: 1918,
    stampCatalogNumber: 'POFIS 1',
    perforation: 'Nezoubkovaná',
    printType: 'Kamenotisk',
    cancellation: 'Nerazítkovaná',
    dimensions: '30x25mm',
    estimatedValue: '500 Kč',
    storageLocation: 'Album č. 1',
    historicalContext: 'První československé známky designované Alfonsem Muchou.',
  },
  {
    title: 'Holubice 50h modrá',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Modrá známka Holubice z roku 1920, symbol míru po první světové válce.',
    condition: 'Velmi dobrá',
    material: 'Papír',
    period: 'První republika',
    periodFrom: 1920,
    periodTo: 1925,
    stampYear: 1920,
    stampCatalogNumber: 'POFIS 145',
    perforation: '13¾',
    printType: 'Hlubotisk',
    cancellation: 'Praha 1',
    dimensions: '25x20mm',
    estimatedValue: '150 Kč',
    storageLocation: 'Album č. 1',
    historicalContext: 'Poválečné období, budování státu.',
  },
  {
    title: 'T.G. Masaryk 1Kč',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Známka s portrétem prezidenta T.G. Masaryka, jednokorunová hodnota.',
    condition: 'Dobrá',
    material: 'Papír',
    period: 'První republika',
    periodFrom: 1918,
    periodTo: 1938,
    stampYear: 1925,
    stampCatalogNumber: 'POFIS 190',
    perforation: '14',
    printType: 'Rotační hlubotisk',
    cancellation: 'Brno 2',
    dimensions: '22x27mm',
    estimatedValue: '80 Kč',
    storageLocation: 'Album č. 1',
    historicalContext: 'Období prezidentování T.G. Masaryka.',
  },
  {
    title: 'Lidice 1942 - černá',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Smuteční známka k výročí vyhlazení Lidic. Černý tisk na bílém papíře.',
    condition: 'Výborná',
    material: 'Papír',
    period: 'Druhá světová válka',
    periodFrom: 1942,
    periodTo: 1945,
    stampYear: 1942,
    stampCatalogNumber: 'POFIS 99 (Londýn)',
    perforation: '12',
    printType: 'Ocelotisk',
    cancellation: 'Nerazítkovaná',
    dimensions: '35x25mm',
    estimatedValue: '2000 Kč',
    storageLocation: 'Album č. 2',
    historicalContext: 'Připomínka nacistického zločinu v Lidicích.',
  },
  {
    title: 'Sokol - V. všesokolský slet',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Příležitostná známka k V. všesokolskému sletu v roce 1948.',
    condition: 'Velmi dobrá',
    material: 'Papír',
    period: 'Poválečné období',
    periodFrom: 1945,
    periodTo: 1948,
    stampYear: 1948,
    stampCatalogNumber: 'POFIS 482',
    perforation: '12½',
    printType: 'Hlubotisk',
    cancellation: 'Praha - Slet',
    dimensions: '40x23mm',
    estimatedValue: '120 Kč',
    storageLocation: 'Album č. 2',
    historicalContext: 'Poslední Sokolský slet před komunistickým pučem.',
  },
  {
    title: 'Kosmonaut Gagarin 1961',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Známka k příležitosti prvního letu člověka do vesmíru.',
    condition: 'Výborná',
    material: 'Papír',
    period: 'Socialismus',
    periodFrom: 1948,
    periodTo: 1989,
    stampYear: 1961,
    stampCatalogNumber: 'POFIS 1199',
    perforation: '11½',
    printType: 'Ofset',
    cancellation: 'Nerazítkovaná',
    dimensions: '30x40mm',
    estimatedValue: '200 Kč',
    storageLocation: 'Album č. 3',
    historicalContext: 'Období kosmických závodů a studenéválky.',
  },
  {
    title: 'Pražské jaro 1968',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Známka vydaná během Pražského jara 1968. Symbol svobody.',
    condition: 'Velmi dobrá',
    material: 'Papír',
    period: 'Socialismus',
    periodFrom: 1948,
    periodTo: 1989,
    stampYear: 1968,
    stampCatalogNumber: 'POFIS 1695',
    perforation: '11½x12',
    printType: 'Ofset',
    cancellation: 'Praha',
    dimensions: '23x40mm',
    estimatedValue: '300 Kč',
    storageLocation: 'Album č. 3',
    historicalContext: 'Krátké období uvolnění před okupací.',
  },
  {
    title: 'Sametová revoluce 1989',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Známka vydaná k výročí Sametové revoluce. Symbol srdce a klíče.',
    condition: 'Výborná',
    material: 'Papír',
    period: 'Porevoluční',
    periodFrom: 1989,
    periodTo: 1992,
    stampYear: 1990,
    stampCatalogNumber: 'POFIS 2920',
    perforation: '12x11½',
    printType: 'Ofset multicolor',
    cancellation: 'Nerazítkovaná',
    dimensions: '40x23mm',
    estimatedValue: '50 Kč',
    storageLocation: 'Album č. 4',
    historicalContext: 'Pád komunistického režimu a návrat demokracie.',
  },
  {
    title: 'Europa CEPT 1995',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Známka řady Europa věnovaná míru a svobodě.',
    condition: 'Výborná',
    material: 'Papír',
    period: 'Česká republika',
    periodFrom: 1993,
    periodTo: 2000,
    stampYear: 1995,
    stampCatalogNumber: 'POFIS 72',
    perforation: '11½',
    printType: 'Ofset',
    cancellation: 'Nerazítkovaná',
    dimensions: '40x30mm',
    estimatedValue: '80 Kč',
    storageLocation: 'Album č. 4',
    historicalContext: 'Česká republika jako člen evropské poštovní unie.',
  },
  {
    title: 'Přítisk Hradčany - převrácený',
    category: 'filatelie',
    findingType: 'STAMP',
    description: 'Velmi vzácná chybotiská - přítisk je převrácený. Sběratelská rarita.',
    condition: 'Dobrá',
    material: 'Papír',
    period: 'Vznik ČSR',
    periodFrom: 1918,
    periodTo: 1920,
    stampYear: 1919,
    stampCatalogNumber: 'POFIS 43PT',
    perforation: '11½',
    printType: 'Kamenotisk',
    cancellation: 'Nerazítkovaná',
    dimensions: '30x25mm',
    estimatedValue: '15000 Kč',
    storageLocation: 'Trezor',
    historicalContext: 'Chybotisk z období vzniku republiky.',
  },
];

// Militárie - 4 nálezy
const militaryFindings = [
  {
    title: 'Rakousko-uherská přezka',
    category: 'militarie',
    findingType: 'MILITARY',
    description: 'Mosazná opasková přezka Rakousko-uherské armády s dvouhlavým orlem a heslem "Gott mit uns".',
    condition: 'Dobrá',
    material: 'Mosaz',
    period: 'První světová válka',
    periodFrom: 1914,
    periodTo: 1918,
    weight: 85,
    dimensions: '65x45mm',
    army: 'Rakousko-Uhersko',
    conflict: 'První světová válka',
    unit: 'Pěchota',
    authenticity: 'Originál',
    depth: 30,
    historicalContext: 'Období rozpadu Rakousko-Uherska.',
  },
  {
    title: 'Německá identifikační známka WW2',
    category: 'militarie',
    findingType: 'MILITARY',
    description: 'Hliníková identifikační známka (Erkennungsmarke) německého vojáka z 2. světové války. Částečně čitelné číslo jednotky.',
    condition: 'Poškozená',
    material: 'Hliník',
    period: 'Druhá světová válka',
    periodFrom: 1939,
    periodTo: 1945,
    weight: 12,
    dimensions: '70x50mm (půlená)',
    army: 'Německo - Wehrmacht',
    conflict: 'Druhá světová válka',
    unit: 'Neidentifikováno',
    authenticity: 'Originál',
    depth: 45,
    historicalContext: 'Období nacistické okupace Československa.',
  },
  {
    title: 'Čepicový odznak ČS legií',
    category: 'militarie',
    findingType: 'MILITARY',
    description: 'Bronzový čepicový odznak československých legionářů z období první světové války. Lev se štítem.',
    condition: 'Velmi dobrá',
    material: 'Bronz',
    period: 'První světová válka',
    periodFrom: 1914,
    periodTo: 1920,
    weight: 25,
    dimensions: '35x40mm',
    army: 'Československé legie',
    conflict: 'První světová válka',
    unit: 'Legie v Rusku',
    authenticity: 'Originál',
    depth: 22,
    historicalContext: 'Období boje za samostatnost Československa.',
  },
  {
    title: 'Sovětská hvězda s M/S',
    category: 'militarie',
    findingType: 'MILITARY',
    description: 'Čepicová hvězda sovětské armády s kladivem a srpem. Rudá smalt na mosazi.',
    condition: 'Dobrá',
    material: 'Mosaz, smalt',
    period: 'Studená válka',
    periodFrom: 1945,
    periodTo: 1989,
    weight: 18,
    dimensions: '32mm',
    army: 'Sovětský svaz - Rudá armáda',
    conflict: 'Okupace 1968',
    unit: 'Neznámá',
    authenticity: 'Originál',
    depth: 15,
    historicalContext: 'Období sovětské přítomnosti v Československu.',
  },
];

// Terénní nálezy (detektoráři) - 4 nálezy
const terrainFindings = [
  {
    title: 'Stříbrný prsten se znakem',
    category: 'šperky',
    findingType: 'TERRAIN',
    description: 'Stříbrný prsten s erbovním znakem, pravděpodobně šlechtického původu.',
    condition: 'Velmi dobrá',
    material: 'Stříbro',
    period: 'Baroko',
    periodFrom: 1650,
    periodTo: 1750,
    weight: 8.5,
    dimensions: 'Velikost 18',
    detectorSignal: 'Stabilní, 25-28',
    landType: 'Pole',
    soilConditions: 'Hlinitá půda',
    depth: 18,
    historicalContext: 'Období barokní kultury v Čechách.',
  },
  {
    title: 'Bronzová spona - fibula',
    category: 'archeologie',
    findingType: 'TERRAIN',
    description: 'Římská bronzová fibula (spona na oděv) typu Aucissa. Vzácný nález z doby římské.',
    condition: 'Fragmentární',
    material: 'Bronz',
    period: 'Doba římská',
    periodFrom: 50,
    periodTo: 200,
    weight: 15,
    dimensions: '45x20mm',
    detectorSignal: 'Nízký, 15-18',
    landType: 'Louka',
    soilConditions: 'Písčitá',
    depth: 35,
    historicalContext: 'Období římského vlivu na území dnešní ČR.',
  },
  {
    title: 'Olověná plomba cechu',
    category: 'řemesla',
    findingType: 'TERRAIN',
    description: 'Olověná cechovní plomba s vyobrazením nůžek - cech krejčích.',
    condition: 'Dobrá',
    material: 'Olovo',
    period: 'Renesance',
    periodFrom: 1500,
    periodTo: 1600,
    weight: 22,
    dimensions: '28mm průměr',
    detectorSignal: 'Silný, 40+',
    landType: 'Historické centrum',
    soilConditions: 'Stavební suť',
    depth: 55,
    historicalContext: 'Období rozkvětu řemeslných cechů.',
  },
  {
    title: 'Železná podkova - gotická',
    category: 'zemědělství',
    findingType: 'TERRAIN',
    description: 'Gotická podkova typického tvaru s charakteristickými otvory pro hřeby.',
    condition: 'Zkorodovaná',
    material: 'Železo',
    period: 'Gotika',
    periodFrom: 1300,
    periodTo: 1450,
    weight: 180,
    dimensions: '120x110mm',
    detectorSignal: 'Velký železný signál',
    landType: 'Polní cesta',
    soilConditions: 'Jílovitá půda',
    depth: 40,
    historicalContext: 'Období středověkého zemědělství.',
  },
];

async function main() {
  console.log('🔍 Hledám uživatele zidekfilip...');
  
  // Najdi uživatele podle nickname nebo emailu
  const user = await prisma.user.findFirst({
    where: {
      OR: [
        { nickname: { contains: 'zidekfilip', mode: 'insensitive' } },
        { email: { contains: 'zidekfilip', mode: 'insensitive' } },
        { nickname: { contains: 'zidek', mode: 'insensitive' } },
        { email: { contains: 'zidek', mode: 'insensitive' } },
      ],
    },
  });

  if (!user) {
    // Vypíšeme všechny uživatele pro debug
    const allUsers = await prisma.user.findMany({
      select: { id: true, email: true, nickname: true },
    });
    console.log('❌ Uživatel zidekfilip nenalezen!');
    console.log('📋 Existující uživatelé:');
    allUsers.forEach(u => console.log(`  - ${u.email} (${u.nickname || 'bez nickname'}) [${u.id}]`));
    return;
  }

  console.log(`✅ Nalezen uživatel: ${user.email} (${user.nickname || 'bez nickname'})`);
  console.log(`   ID: ${user.id}`);

  // Připrav všechny nálezy
  const allFindings = [
    ...coinFindings.map((f, i) => ({ ...f, locationIndex: i })),
    ...stampFindings.map((f, i) => ({ ...f, locationIndex: (i + 6) % 20 })),
    ...militaryFindings.map((f, i) => ({ ...f, locationIndex: (i + 16) % 20 })),
    ...terrainFindings.map((f, i) => ({ ...f, locationIndex: (i + 10) % 20 })),
  ];

  console.log(`\n📝 Vytvářím ${allFindings.length} nálezů...`);

  let created = 0;
  for (const finding of allFindings) {
    const location = locations[finding.locationIndex];
    const { locationIndex, ...findingData } = finding;

    // Generuj náhodné datum v posledních 2 letech
    const randomDays = Math.floor(Math.random() * 730);
    const findingDate = new Date();
    findingDate.setDate(findingDate.getDate() - randomDays);

    try {
      await prisma.finding.create({
        data: {
          userId: user.id,
          title: findingData.title,
          latitude: location.lat + (Math.random() - 0.5) * 0.01, // Mírná variace
          longitude: location.lng + (Math.random() - 0.5) * 0.01,
          date: findingDate,
          description: findingData.description,
          category: findingData.category,
          findingType: findingData.findingType,
          condition: findingData.condition,
          material: findingData.material,
          period: findingData.period,
          periodFrom: findingData.periodFrom,
          periodTo: findingData.periodTo,
          weight: findingData.weight,
          dimensions: findingData.dimensions,
          locationName: location.name,
          historicalContext: findingData.historicalContext,
          
          // COIN specifická
          denomination: findingData.denomination,
          mintYear: findingData.mintYear,
          mint: findingData.mint,
          catalogNumber: findingData.catalogNumber,
          grade: findingData.grade,
          
          // STAMP specifická
          stampYear: findingData.stampYear,
          stampCatalogNumber: findingData.stampCatalogNumber,
          perforation: findingData.perforation,
          printType: findingData.printType,
          cancellation: findingData.cancellation,
          
          // MILITARY specifická
          army: findingData.army,
          conflict: findingData.conflict,
          unit: findingData.unit,
          authenticity: findingData.authenticity,
          
          // TERRAIN specifická
          detectorSignal: findingData.detectorSignal,
          landType: findingData.landType,
          soilConditions: findingData.soilConditions,
          depth: findingData.depth,
          
          // Další
          estimatedValue: findingData.estimatedValue,
          storageLocation: findingData.storageLocation,
          
          // Nastavení viditelnosti
          visibility: 'PRIVATE',
          isPublic: false,
        },
      });
      created++;
      console.log(`  ✓ ${findingData.title} (${findingData.findingType}) - ${location.name}`);
    } catch (error) {
      console.error(`  ✗ Chyba při vytváření "${findingData.title}":`, error);
    }
  }

  console.log(`\n✅ Hotovo! Vytvořeno ${created} nálezů pro uživatele ${user.email}`);
  console.log(`   - Mince: 6`);
  console.log(`   - Známky: 10`);
  console.log(`   - Militárie: 4`);
  console.log(`   - Terénní nálezy: 4`);
}

main()
  .catch((e) => {
    console.error('❌ Chyba:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

